### ISSUE TITLE
Why streams and not async/await for links generation?

### ISSUE THREAD

**Issue by nick-skriabin** [blackmenthor/flutter-branch-io#26]
Here's the thing, in out app there are few different places where the link can be generated, after the link is created we need to open a share dialog with a content-specific text and data (e.g. images) with the generated link included. The thing is that at this moment there's no way to determine at what place of the app the link was generated and there's no way to associate the link with the appropriate content in the app.

Let me clarify a little: e.g., we have a post (caption+image) and it has a share button, also we have user profile with an "invite" button. Both share and invite buttons should generate a branch link that will be passed to a share plugin (system share dialog). In the plugin itself we're specifying some text related to a particular case (sharing the post or sharing the invite link). The text if different, of course, but when the stream receives the link it lacks the context where the link was generated and we cannot determine whether it was a post share or an invitation.

Probably, it will be much more convenient to be able to receive a link right where you're calling `FlutterBranchIoPlugin.generateLink(...)`

**Comment by RodrigoSMarques** [comment]
Hi @nicholasrq 
I believe that this plugin is abandoned. There are many issues waiting to be answered.
See this here: https://pub.dev/packages/flutter_branch_sdk

**Comment by nick-skriabin** [comment]
@RodrigoSMarques thanks a lot! it looks like a better solution, because I had to fix many things on my side for current implementation to make it work

closing this one then
