### ISSUE TITLE
Flutter Build Release Crash

### ISSUE THREAD

**Issue by vagners2** [blackmenthor/flutter-branch-io#30]
Hi,
doesn't compile, flutter build apk --release

Execution failed for task ':flutter_android_lifecycle:verifyReleaseResources'. 
 error: resource android:attr/fontVariationSettings not found.
 error: resource android:attr/ttcIndex not found.

I remove plugin is build success... 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale pt-BR)

**Comment by mustela** [comment]
Hey guys, we are having the same issue, any clue what could be causing it or any workaround? 

Thanks!

**Comment by RodrigoSMarques** [comment]
Hello guys.
I don't know if it's the best solution. But as I was also facing some problems, I decided to create a new plugin.
If you want to test: https://pub.dev/packages/flutter_branch_sdk
I have applications published with this plugin

**Comment by mustela** [comment]
@RodrigoSMarques yes, we switched to your plugin and it's working, thanks a lot!

**Comment by vagners2** [comment]
> Hello guys.
> I don't know if it's the best solution. But as I was also facing some problems, I decided to create a new plugin.
> If you want to test: https://pub.dev/packages/flutter_branch_sdk
> I have applications published with this plugin
