### ISSUE TITLE
README section about iOS could use some clarification

### ISSUE THREAD

**Issue by ijt** [blackmenthor/flutter-branch-io#34]
Hiya. I'm looking at the README section about iOS and thinking maybe there is a typo:

<img width="942" alt="Screen Shot 2020-03-12 at 9 19 14 PM" src="https://user-images.githubusercontent.com/15530/76589424-4cdba300-64a7-11ea-8b39-b7bfb939b91d.png">

The code there only mentions Android but does not mention iOS at all.

**Comment by RodrigoSMarques** [comment]
Hi @ijt 
I believe that this plugin is abandoned. There are many issues waiting to be answered.
See this here: https://pub.dev/packages/flutter_branch_sdk

**Comment by ijt** [comment]
Hi @RodrigoSMarques, right, I ended up using your plugin instead. Thanks for making it available!
