### ISSUE TITLE
Error when run on IOS

### ISSUE THREAD

**Issue by docaohuynh** [blackmenthor/flutter-branch-io#4]
Hi Blackmenthor
I have got error when run on IOS like this. How do I solve problem
 ```
[!] The following Swift pods cannot yet be integrated as static libraries:
    The Swift pod `flutter_branch_io_plugin` depends upon `Branch`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:135:in `verify_swift_pods_have_module_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:415:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:118:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
```

**Comment by blackmenthor** [comment]
Hi @docaohuynh 

actually i haven't had time to develop ios's version on this package, all it does is just add 'Branch' dependency inside the podspec.

And for your particular error, maybe i'll conside removing 'Branch' dependency since i haven't used em.

However, i was able to integrate Branch core features on my Flutter Project's iOS side, but not inside this package.

All i do is just follow these instruction https://docs.branch.io/pages/apps/ios/ and modify the AppDelegate (dot m or dot swift depending on your configs) and it works like a charm.

If you still have any question, please ask me further, maybe i'll create a sample project for you to follow.

**Comment by blackmenthor** [comment]
Closed bcs iOS side is already implemented

**Comment by willvlad** [comment]
I am getting the same error. I've installed branch as per branch's ios steps, but your plugin is throwing the same error. Where is the Branch dependency in your plugin that needs to be removed?
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `flutter_branch_io_plugin` depends upon `Branch`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**Comment by blackmenthor** [comment]
Hi, Will

is adding this line below inside your project's Podfile solves your problem?

`
pod 'Branch'
`

if it is, i'll add this instruction inside the README

Thanks, Angga.

**Comment by blackmenthor** [comment]
Closed due to inactivity

**Comment by BasedMusa** [comment]
@blackmenthor Just wanted to clarify that your answer is the solution,  I have experienced this in the past as well, sometimes you need manually run this command to make sure that dependency files are downloaded into ios.

Although first, you need to go to the ios folder then run this command, so this would be proper fix to this issue.

**Go to the root of your Flutter project, then:** 
```Bash
cd ios
pod install
```

**Comment by lucas-sesti** [comment]
Update! I tried to install the flutter branch io, and i get the same error, but, i fixed adding: pod 'Branch', :modular_headers => true
