### ISSUE TITLE
Clarification re Change the MainActivity class to extend FlutterBranchIOActivity

### ISSUE THREAD

**Issue by willvlad** [blackmenthor/flutter-branch-io#8]
Hi 

when you say Change the MainActivity class to extend FlutterBranchIOActivity
what do you mean needs to be done exactly? My MainActivity looks like this:

```
package com.xxx.xxx;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;
import com.anggach.flutterandroidlifecycle.FlutterAndroidLifecycleActivity;

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);


//  added this to make the fb stuff below work
    AppEventsLogger logger = AppEventsLogger.newLogger(this);
    logger.logEvent("opened the android app fb");
  }
}
```
Should I replace public class MainActivity extends FlutterActivity  with public class MainActivity extends FlutterBranchIOActivity?? It breaks the app...

**Comment by blackmenthor** [comment]
Hi Will,

Thanks for opening the issue,
So it's my bad, i actually change how the plugin works inside Flutter but i haven't update the instruction inside README.MD

i changed the instruction just now, and maybe you can try once again and tell me is it working inside your project?

Thanks, Angga.

**Comment by willvlad** [comment]
Hi Angga

I still don't quite understand - how would you change the code above?

**Comment by blackmenthor** [comment]
Hi Will,

I updated the instructions on the README, basically your MainActivity should extend FlutterAndroidLifecycleActivity rather than FlutterBranchIOActivity, the dependencies is already included inside this library

**Comment by blackmenthor** [comment]
Closed due to inactivity

**Comment by BasedMusa** [comment]
What about the ones using FlutterFragmentActivity because of other plugins?
